### ISSUE TITLE
nixos: isos are hybrid now :)

### ISSUE THREAD

**Issue by makefu** [FrozenCow/distscraper#8]
see: https://nixos.org/wiki/Installing_NixOS_from_a_USB_stick#Using_dd

as of nixos 15.09 the isos come as isohybrid, they can be dd'ed directly onto an usb-stick

**Comment by FrozenCow** [comment]
Indeed. I was waiting for the release, but I forgot about it. Thanks for the reminder, i'll get right on it.

**Comment by FrozenCow** [comment]
The scraper is added (https://github.com/FrozenCow/distscraper/commit/7fba70ed17dcacc85a1647649c92c78cd7b1fda6) and should be running in the next hour or so.

**Comment by makefu** [comment]
Thanks!
